# Generated by Django 5.2.6 on 2025-09-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_animal_birth_date_alter_animal_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='idade'),
        ),
    ]
