# Generated by Django 5.2.6 on 2025-09-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_animal_age'),
        ('cadastro', '0003_remove_weight_fields_and_add_weighing'),
    ]

    operations = [
    ]
